package com.example.huiyiqiandaotv.beans;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.huiyiqiandaotv.beans.BaoCunBean;
import com.example.huiyiqiandaotv.beans.BenDiRenShuBean;
import com.example.huiyiqiandaotv.beans.MoShengRenBean;
import com.example.huiyiqiandaotv.beans.QianDaoId;
import com.example.huiyiqiandaotv.beans.ShiBieJiLuBean;
import com.example.huiyiqiandaotv.beans.ShiPingBean;
import com.example.huiyiqiandaotv.beans.TanChuangBean;

import com.example.huiyiqiandaotv.beans.BaoCunBeanDao;
import com.example.huiyiqiandaotv.beans.BenDiRenShuBeanDao;
import com.example.huiyiqiandaotv.beans.MoShengRenBeanDao;
import com.example.huiyiqiandaotv.beans.QianDaoIdDao;
import com.example.huiyiqiandaotv.beans.ShiBieJiLuBeanDao;
import com.example.huiyiqiandaotv.beans.ShiPingBeanDao;
import com.example.huiyiqiandaotv.beans.TanChuangBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig baoCunBeanDaoConfig;
    private final DaoConfig benDiRenShuBeanDaoConfig;
    private final DaoConfig moShengRenBeanDaoConfig;
    private final DaoConfig qianDaoIdDaoConfig;
    private final DaoConfig shiBieJiLuBeanDaoConfig;
    private final DaoConfig shiPingBeanDaoConfig;
    private final DaoConfig tanChuangBeanDaoConfig;

    private final BaoCunBeanDao baoCunBeanDao;
    private final BenDiRenShuBeanDao benDiRenShuBeanDao;
    private final MoShengRenBeanDao moShengRenBeanDao;
    private final QianDaoIdDao qianDaoIdDao;
    private final ShiBieJiLuBeanDao shiBieJiLuBeanDao;
    private final ShiPingBeanDao shiPingBeanDao;
    private final TanChuangBeanDao tanChuangBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        baoCunBeanDaoConfig = daoConfigMap.get(BaoCunBeanDao.class).clone();
        baoCunBeanDaoConfig.initIdentityScope(type);

        benDiRenShuBeanDaoConfig = daoConfigMap.get(BenDiRenShuBeanDao.class).clone();
        benDiRenShuBeanDaoConfig.initIdentityScope(type);

        moShengRenBeanDaoConfig = daoConfigMap.get(MoShengRenBeanDao.class).clone();
        moShengRenBeanDaoConfig.initIdentityScope(type);

        qianDaoIdDaoConfig = daoConfigMap.get(QianDaoIdDao.class).clone();
        qianDaoIdDaoConfig.initIdentityScope(type);

        shiBieJiLuBeanDaoConfig = daoConfigMap.get(ShiBieJiLuBeanDao.class).clone();
        shiBieJiLuBeanDaoConfig.initIdentityScope(type);

        shiPingBeanDaoConfig = daoConfigMap.get(ShiPingBeanDao.class).clone();
        shiPingBeanDaoConfig.initIdentityScope(type);

        tanChuangBeanDaoConfig = daoConfigMap.get(TanChuangBeanDao.class).clone();
        tanChuangBeanDaoConfig.initIdentityScope(type);

        baoCunBeanDao = new BaoCunBeanDao(baoCunBeanDaoConfig, this);
        benDiRenShuBeanDao = new BenDiRenShuBeanDao(benDiRenShuBeanDaoConfig, this);
        moShengRenBeanDao = new MoShengRenBeanDao(moShengRenBeanDaoConfig, this);
        qianDaoIdDao = new QianDaoIdDao(qianDaoIdDaoConfig, this);
        shiBieJiLuBeanDao = new ShiBieJiLuBeanDao(shiBieJiLuBeanDaoConfig, this);
        shiPingBeanDao = new ShiPingBeanDao(shiPingBeanDaoConfig, this);
        tanChuangBeanDao = new TanChuangBeanDao(tanChuangBeanDaoConfig, this);

        registerDao(BaoCunBean.class, baoCunBeanDao);
        registerDao(BenDiRenShuBean.class, benDiRenShuBeanDao);
        registerDao(MoShengRenBean.class, moShengRenBeanDao);
        registerDao(QianDaoId.class, qianDaoIdDao);
        registerDao(ShiBieJiLuBean.class, shiBieJiLuBeanDao);
        registerDao(ShiPingBean.class, shiPingBeanDao);
        registerDao(TanChuangBean.class, tanChuangBeanDao);
    }
    
    public void clear() {
        baoCunBeanDaoConfig.clearIdentityScope();
        benDiRenShuBeanDaoConfig.clearIdentityScope();
        moShengRenBeanDaoConfig.clearIdentityScope();
        qianDaoIdDaoConfig.clearIdentityScope();
        shiBieJiLuBeanDaoConfig.clearIdentityScope();
        shiPingBeanDaoConfig.clearIdentityScope();
        tanChuangBeanDaoConfig.clearIdentityScope();
    }

    public BaoCunBeanDao getBaoCunBeanDao() {
        return baoCunBeanDao;
    }

    public BenDiRenShuBeanDao getBenDiRenShuBeanDao() {
        return benDiRenShuBeanDao;
    }

    public MoShengRenBeanDao getMoShengRenBeanDao() {
        return moShengRenBeanDao;
    }

    public QianDaoIdDao getQianDaoIdDao() {
        return qianDaoIdDao;
    }

    public ShiBieJiLuBeanDao getShiBieJiLuBeanDao() {
        return shiBieJiLuBeanDao;
    }

    public ShiPingBeanDao getShiPingBeanDao() {
        return shiPingBeanDao;
    }

    public TanChuangBeanDao getTanChuangBeanDao() {
        return tanChuangBeanDao;
    }

}
